### ISSUE TITLE
[Suggestion] GitHub Actions Bot Identity Configuration Action / PR Creation Action

### ISSUE THREAD

**Issue by kevinmatthes** [devops-actions/actionlint#30]
At the moment, the Git identity in `update-actionlint.yml` is set conditionally from within a PowerShell script.  However, the used data is not correct such that the resulting commit would not be assigned to the correct user.  I would like to suggest to apply the following Action to setup the Git identity for committing:  https://github.com/fregante/setup-git-user.  It is a lightweight composite Action that will only configure the GitHub Actions bot as user.  Due to this centralised approach of configuring the relevant information for committing, the workflow would become more readable which would enhance the maintainability.

Furthermore, I would like to discuss the option to apply a PR creation Action in order to submit the made changes to GitHub.  I worked with https://github.com/peter-evans/create-pull-request, so far, and the configuration options allow for different optimisations.  For example, the Action can be set to overwrite existing PRs it created which resembles Dependabot's behaviour to close superseded PRs such that only one open update PR would be kept.  The Action will update the existing PR by force-pushing to the branch it has created.  In addition, also the Git identity can be set to custom values; by default, valid settings are deduced from the publicly available data of the user invoking the workflow which might be an alternative to the Action mentioned above.  In each case, only uncommitted changes will be committed by the PR creation Action, commits created before the Action was called will be also part of resulting PR but can be made using a different Git identity.  However, to use this Action, it is required to allow for the creation and merging of PRs by workflows in the repository settings.

What do you think about these ideas, @rajbos?

**Comment by rajbos** [comment]
> At the moment, the Git identity in update-actionlint.yml is set conditionally from within a PowerShell script. However, the used data is not correct such that the resulting commit would not be assigned to the correct user. I would like to suggest to apply the following Action to setup the Git identity for committing: https://github.com/fregante/setup-git-user. It is a lightweight composite Action that will only configure the GitHub Actions bot as user. Due to this centralised approach of configuring the relevant information for committing, the workflow would become more readable which would enhance the maintainability.

Honestly I do not care to much about the user that makes the commit. It's clear that it is coming from a bot. Extracting this to an action would work ofc and would remove some cruft from the pwsh script indeed.


> Furthermore, I would like to discuss the option to apply a PR creation Action in order to submit the made changes to GitHub. I worked with https://github.com/peter-evans/create-pull-request, so far, and the configuration options allow for different optimisations. For example, the Action can be set to overwrite existing PRs it created which resembles Dependabot's behaviour to close superseded PRs such that only one open update PR would be kept. The Action will update the existing PR by force-pushing to the branch it has created. In addition, also the Git identity can be set to custom values; by default, valid settings are deduced from the publicly available data of the user invoking the workflow which might be an alternative to the Action mentioned above. In each case, only uncommitted changes will be committed by the PR creation Action, commits created before the Action was called will be also part of resulting PR but can be made using a different Git identity. However, to use this Action, it is required to allow for the creation and merging of PRs by workflows in the repository settings.

That would mean we'd need to pull the logic for the if statement out of the pwsh script, return it as output from the script and then have an `if` expression in the PR creation step. Seems unnecessary for such a simple line of code.  I think it would rather make sense to just extract the script code into an actual pwsh script file, so that it becomes easier to run the "workflow" locally during development as well, since the script is completely self contained.
