### ISSUE TITLE
SHELLCHECK_OPTS is not passed to docker

### ISSUE THREAD

**Issue by piotrekkr** [devops-actions/actionlint#40]
I wrote [an issue](https://github.com/rhysd/actionlint/issues/395) about enabling use of `.shellcheckrc` file in `actionlint` but then I was informed that `SHELLCHECK_OPTS` should work just fine. Unfortunately this env var is not passed by this action to docker container. 

Maybe you could consider adding `-e SHELLCHECK_OPTS` to `docker run` or add input parameter to action and pass it as `-e SHELLCHECK_OPTS="${{ inputs.shellcheck_opts }}"` or something like this? 

Thank you :pray:

**Comment by rajbos** [comment]
Fixed by releasing it as [v0.1.3](https://github.com/devops-actions/actionlint/releases/tag/v0.1.3). Thanks @piotrekkr !
